const tierStyles = {
  'Human outcome evidence': 'bg-emerald-100 text-emerald-800',
  'Guideline/framework evidence': 'bg-blue-100 text-blue-800',
  'Preclinical/translational evidence': 'bg-amber-100 text-amber-900',
}

const homeCards = [
  { title: 'CHALLENGE Trial', evidenceTier: 'Human outcome evidence', population: 'Resected stage III or high-risk stage II colon cancer after adjuvant chemotherapy', keyFinding: 'A Phase 3 randomized trial found that a structured 3-year exercise program improved disease-free survival.', caveat: 'This does not mean exercise replaces oncology treatment.' },
  { title: 'Cancer-Related Fatigue', evidenceTier: 'Guideline/framework evidence', population: 'Cancer survivors across treatment phases', keyFinding: 'Exercise is one of the best-supported nonpharmacologic interventions for fatigue.', caveat: 'Dose should be individualized and symptom-aware.' },
  { title: 'Muscle Preservation', evidenceTier: 'Guideline/framework evidence', population: 'Patients at risk of deconditioning, sarcopenia, or cachexia', keyFinding: 'Skeletal muscle supports strength, glucose disposal, physical reserve, and treatment resilience.', caveat: 'Walking helps, but resistance training is often necessary when safe.' },
]

const resultMetrics = [
  { label: '5-year DFS', exerciseValue: '80.3%', comparatorValue: '73.9%', interpretation: 'Higher disease-free survival with structured exercise.' },
  { label: '8-year OS', exerciseValue: '90.3%', comparatorValue: '83.2%', interpretation: 'Overall survival findings were consistent with benefit.' },
  { label: 'MSK adverse events', exerciseValue: '18.5%', comparatorValue: '11.5%', interpretation: 'Higher adverse events support supervised progression.' },
]

const fittvp = [
  ['Frequency', 'How often sessions occur each week.'], ['Intensity', 'How hard sessions feel (RPE 0–10).'], ['Time', 'How long each session lasts.'], ['Type', 'Resistance, aerobic, balance, mobility.'], ['Volume', 'Total weekly work across sessions.'], ['Progression', 'How dose changes over time with safety checks.'],
]

function Badge({ tier }) { return <span className={`inline-block rounded-full px-3 py-1 text-xs font-semibold ${tierStyles[tier] || 'bg-slate-100'}`}>{tier}</span> }
function Card({ children }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">{children}</section> }

export default function App() {
  return <main className="mx-auto max-w-6xl space-y-6 p-4 md:p-8">
    <Card><h1 className="text-3xl font-bold">Exercise Oncology Is Not Wellness Advice</h1><p className="mt-2 text-lg">Structured exercise is becoming a serious part of cancer survivorship care.</p><p className="mt-3">For years, many cancer survivors were told to “stay active if you feel up to it.” That advice is not wrong, but it is incomplete. Exercise oncology is about prescribing the right type, dose, progression, and safety modifications for the individual patient.</p><div className="mt-4 rounded-lg border-l-4 border-rose-700 bg-rose-50 p-4 text-sm">This site is for education only. It is not medical advice. It does not replace oncology care, surgery, chemotherapy, radiation, immunotherapy, rehabilitation, or individualized medical guidance. Cancer patients should discuss exercise plans with their oncology team, especially during active treatment or when blood counts, neuropathy, bone metastases, surgical restrictions, cardiopulmonary disease, or severe fatigue are present.</div></Card>

    <section className="grid gap-4 md:grid-cols-3">{homeCards.map((c)=><Card key={c.title}><Badge tier={c.evidenceTier}/><h3 className="mt-2 font-semibold">{c.title}</h3><p className="text-sm mt-2">{c.population}</p><p className="mt-2">{c.keyFinding}</p><p className="mt-2 text-sm text-slate-700"><strong>Caveat:</strong> {c.caveat}</p></Card>)}</section>

    <Card><h2 className="text-2xl font-bold">The CHALLENGE Trial</h2><p className="mt-2 text-sm">Courneya KS, Vardy JL, O’Callaghan CJ, et al.; CHALLENGE Investigators. <em>NEJM</em>. 2025;393(1):13–25. DOI: 10.1056/NEJMoa2502760. PMID: 40450658.</p><ul className="mt-3 list-disc pl-6 space-y-1 text-sm"><li>Phase 3 randomized controlled trial.</li><li>Population: adults with resected stage III or high-risk stage II colon cancer after adjuvant chemotherapy.</li><li>Intervention: 3-year structured exercise with behavioral support and supervised components.</li><li>Comparator: health-education materials alone.</li><li>Primary outcome: disease-free survival.</li></ul><div className="mt-4 grid gap-3 md:grid-cols-3">{resultMetrics.map((m)=><div key={m.label} className="rounded-lg bg-slate-50 p-3 border"><p className="font-semibold">{m.label}</p><p className="text-sm">Exercise: {m.exerciseValue}</p><p className="text-sm">Health education: {m.comparatorValue}</p><p className="text-xs mt-1 text-slate-600">{m.interpretation}</p></div>)}</div><div className="mt-4 rounded-lg border-l-4 border-amber-600 bg-amber-50 p-4 text-sm"><strong>Do not misread this trial:</strong> This was not exercise instead of chemotherapy. It was structured exercise after surgery and adjuvant chemotherapy. The comparator was health-education materials alone, not a matched supervised attention-control intervention.</div></Card>

    <Card><h2 className="text-2xl font-bold">Not All Evidence Means the Same Thing</h2><div className="mt-3 space-y-3 text-sm"><p><strong>Tier 1: Human outcome evidence</strong> — CHALLENGE trial; human RCTs/meta-analyses for fatigue, function, and quality of life.</p><p><strong>Tier 2: Clinical framework and guideline evidence</strong> — FITT-VP, screening, resistance and aerobic training principles, autoregulation, ESMO express update.</p><p><strong>Tier 3: Mechanistic, preclinical, and translational evidence</strong> — myokines, SPARC, oncostatin M, IL-6 signaling, NK-cell mobilization, tumor perfusion, mitochondrial biology.</p><p className="font-semibold text-rose-700">Hard rule: Tier 3 mechanisms are not presented as proven human survival mechanisms.</p></div></Card>

    <Card><h2 className="text-2xl font-bold">Why Muscle Matters</h2><p className="mt-2">Muscle is not just for lifting things. It is physical reserve: strength, balance, glucose disposal, independence, and resilience during treatment.</p><p className="mt-2 text-sm">Clinician framing: Skeletal muscle supports metabolic regulation, functional reserve, insulin-mediated glucose disposal, and treatment tolerance. Inactivity and cancer-related catabolic stress can accelerate sarcopenia/cachexia.</p><p className="mt-2 text-sm">Walking is valuable but may not be enough to preserve muscle. Resistance training is often necessary and should be considered when safe.</p></Card>

    <Card><h2 className="text-2xl font-bold">Why Aerobic Exercise Matters</h2><p className="mt-2">Established benefits include cardiopulmonary reserve, fatigue improvement, vascular function, mitochondrial adaptation, insulin sensitivity, and quality of life.</p><p className="mt-2 text-sm">Emerging/translational mechanisms (e.g., tumor perfusion, immune trafficking) are promising but not established as causal survival mechanisms in humans.</p></Card>

    <Card><h2 className="text-2xl font-bold">Exercise Is a Dose</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{fittvp.map(([k,v])=><div key={k} className="rounded-lg border p-3"><p className="font-semibold">{k}</p><p className="text-sm">{v}</p></div>)}</div><p className="mt-3 text-sm">RPE: 0–10 effort scale (easy, moderate, hard). RIR: repetitions in reserve; 1–3 RIR means 1–3 clean reps left. Educational only—not a universal prescription.</p></Card>

    <Card><h2 className="text-2xl font-bold">Fatigue Is Not Always Fixed by More Rest</h2><p className="mt-2 text-sm">Short-term rest is appropriate during acute illness or severe symptoms. Prolonged inactivity can worsen deconditioning: fatigue → inactivity → muscle loss/lower aerobic capacity → ordinary tasks feel harder → more fatigue. Do not push through severe symptoms; pursue the safest appropriate movement dose.</p></Card>

    <Card><h2 className="text-2xl font-bold">Safety First: Should I Exercise Today?</h2><div className="grid gap-3 md:grid-cols-3 mt-3 text-sm"><div className="rounded-lg bg-emerald-50 border p-3"><p className="font-semibold">Green</p><p>Mild fatigue, stable symptoms, no fever, no new concerning pain, oncology clearance. Action: planned or modified exercise.</p></div><div className="rounded-lg bg-amber-50 border p-3"><p className="font-semibold">Yellow</p><p>Worse fatigue, mild neuropathy/balance change, mild anemia symptoms, soreness, expected treatment flare. Action: reduce volume/complexity and consider supervision.</p></div><div className="rounded-lg bg-rose-50 border p-3"><p className="font-semibold">Red</p><p>Fever/infection, chest pain, syncope, dyspnea at rest, focal bone pain, uncontrolled GI losses/dehydration, new neurologic deficit, clinician restriction. Action: stop and contact team.</p></div></div></Card>

    <Card><h2 className="text-2xl font-bold">Patient Questions</h2><ul className="list-disc pl-6 text-sm space-y-1 mt-2"><li>Can I be referred to an oncology-trained PT, clinical exercise physiologist, or cancer rehabilitation specialist?</li><li>Are there restrictions based on blood counts, neuropathy, bone health, surgery, port, heart/lung status, or treatment plan?</li><li>Is resistance training safe now?</li><li>What aerobic mode is safest now?</li><li>What symptoms should make me stop and call clinic?</li><li>Can my plan be adjusted around chemotherapy cycles?</li></ul></Card>

    <Card><h2 className="text-2xl font-bold">Clinician Track</h2><p className="text-sm mt-2">Exercise should be treated as a structured supportive intervention, not a vague lifestyle suggestion. For eligible patients, the question is what dose, modality, progression, and supervision level are appropriate. Include FITT-VP dosing, contraindication screening, autoregulation around treatment cycles, referral pathways, and CHALLENGE-aligned counseling.</p></Card>

    <Card><h2 className="text-2xl font-bold">Professor Robert Newton Reading List</h2><p className="text-sm mt-2">Professor Robert Newton’s series is recommended reading for those who want a deeper exercise oncology framework. This site summarizes key concepts and adds evidence-tier guardrails for public education.</p><p className="text-sm mt-2">TODO: Add verified Substack URLs before publication.</p></Card>

    <Card><h2 className="text-2xl font-bold">References</h2><ol className="list-decimal pl-6 text-sm space-y-2 mt-2"><li>Courneya KS, Vardy JL, O’Callaghan CJ, et al.; CHALLENGE Investigators. Structured Exercise after Adjuvant Chemotherapy for Colon Cancer. New England Journal of Medicine. 2025;393(1):13–25. DOI: 10.1056/NEJMoa2502760. PMID: 40450658.</li><li>ESMO Clinical Practice Guideline Express Update on the adoption of physical exercise in patients with localised colon cancer. ESMO Open. 2026;11(2):106019. DOI: 10.1016/j.esmoop.2025.106019.</li><li>ACSM exercise oncology guidelines — to verify before final publication.</li><li>Cancer-related fatigue exercise guidelines — to verify before final publication.</li><li>Professor Robert Newton Substack posts — to verify URLs before final publication.</li></ol></Card>
  </main>
}
